# cloudbuild file
steps:
      # install the required packages
    - name: python
      entrypoint: python
      args: ["-m", "pip", "install", "build", "pytest", "Flask", "xlrd", "pandas", "openpyxl", "google-cloud-secret-manager", "--user"]
      
      # Execute the main.py file. This will process the xl file, create required files for terraform
    - name: python
      entrypoint: python
      args: ["main.py", "--user"]
          
    - id: 'terraform'
      name: 'hashicorp/terraform:1.0.0'
      entrypoint: 'sh'
      args:
      - '-c'
      - |
          if [ -d "terraform/" ]; then
            while IFS= read -r line; do
                  echo "Execution for resource : $line"
                  pwd
                  cd $line
                  pwd
                  ls
                  echo "Executing terraform initialize command"
                  terraform init
                  echo "Executing terraform plan command"
                  terraform plan
                  echo "Executing terraform apply command"
                  terraform apply -auto-approve
            done < requested_modules.txt
          else
            echo "terraform folder is Not available ..."
          fi      
