# cloudbuild file
steps:
    - name: python
      entrypoint: python
      args: ["-m", "pip", "install", "--upgrade", "pip"]     
      
      # install the required packages
    - name: python
      entrypoint: python
      args: ["-m", "pip", "install", "build", "pytest", "Flask", "xlrd", "pandas", "openpyxl", "--user"]
      
      # Execute the main.py file
    - name: python
      entrypoint: python
      args: ["main.py", "--user"]
          
    - id: 'terraformf init'
      name: 'hashicorp/terraform:1.0.0'
      entrypoint: 'sh'
      args:
      - '-c'
      - | 
#        if [ -d "terraform/" ]; then
          cd terraform
          echo "Initializing ..."
          terraform init
#        else
#          echo "terraform not available for init"
#        fi
