# cloudbuild file
steps:
       - name: python
         entrypoint: python
         args: ["-m", "pip", "install", "--upgrade", "pip"]     
       - name: python
         entrypoint: python
         args: ["-m", "pip", "install", "build", "pytest", "Flask", "--user"]
       - name: python
         entrypoint: python
         args: ["main.py", "--user"]
          
